services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    ports:
      - "8008:8008"
    volumes:
      - ./synapse-data:/data
    environment:
      - SYNAPSE_SERVER_NAME=yourdomain.com
      # Other Synapse configurations as needed

  rtl-airband-matrix:
    image: seanauff/matrix-rf-bridge
    container_name: matrix-rf-bridge
    volumes:
      - ./recordings:/recordings  # Directory where recordings are saved
      - ./rtl_airband/rtl_airband.conf:/etc/rtl_airband.conf:ro  # Mount the config file
    environment:
      - SYNAPSE_URL=http://synapse:8008
      - BOT_USER=bot_user
      - BOT_PASSWORD=your_bot_password
      - MATRIX_DOMAIN=yourdomain.com
      - SKIP_DISABLED_CHANNELS=true
      - MIN_AUDIO_DURATION=500  # Example: 0.5 seconds (500ms)
      - DELETE_AFTER_UPLOAD=true # default true
    depends_on:
      - synapse